# Generated by Django 4.1 on 2022-08-29 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_remove_chatroom_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='massage',
            new_name='message',
        ),
    ]
