# Generated by Django 4.1 on 2022-08-29 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_massage_attachment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_url',
            field=models.URLField(default='http://images:8001/url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='messages',
            field=models.ManyToManyField(related_name='attachments', to='chat.message'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('name', 'user')},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='message',
        ),
    ]
