# Generated by Django 4.1 on 2022-09-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_attachment_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(related_name='messages', to='chat.attachment'),
        ),
    ]
